services:
  app:
    build: ./
    image: laravel-auths
    container_name: lar-auths-app
    restart: unless-stopped
    volumes:
      - .:/var/www/
    networks:
      - laravel-auths
  mysql:
    image: mysql
    container_name: lar-auths-db
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
        - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel-auths
networks:
  laravel-auths:
    name: laravel-auths
    driver: bridge
