services:
  app:
    build: ./
    image: auths
    container_name: auths-app
    restart: unless-stopped
    volumes:
      - .:/var/www/
    networks:
      - auths
  mysql:
    image: mysql
    container_name: auths-db
    restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
        - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - auths
networks:
  auths:
    name: auths
    driver: bridge
